[window] 
padding = { x = 5 , y = 5}
opacity = 0.8
decorations = "None"

[font]
normal = { family = "Office Code Pro D Light", style = "Light" }
bold = { family = "Office Code Pro D Bold", style = "Bold" }
size = 11

#Offset - ExtraSpace around each character
offset = {x =1, y = 0}

[cursor]
style = { shape = "Underline", blinking = "off" }


