
[window] 
padding = { x = 5 , y = 5}
opacity = 0.85
decorations = "None"

[font]
normal = { family = "JetBrainsMono NF ExtraBold", style = "Bolder" }
bold = { family = "JetBrainsMono NF ExtraBold", style = "Bolder" }
size = 11

#Offset - ExtraSpace around each character
offset = {x =1, y = 0}

[cursor]
style = { shape = "Underline", blinking = "off" }

[general]
import = ["~/.cache/wal/colors-alacritty.toml"]


