[mgr]
show_hidden = false
sort_by = "mtime"
sort_reverse = true
sort_dir_first = true

[opener]
edit = [
	{ run = '"$EDITOR" "$@"', block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
onlyoffice = [
	{ run = 'onlyoffice-desktopeditors "$@"', desc = "OnlyOffice opener" },
]

[open]
prepend_rules = [
	{ name = "*.csv", use = "onlyoffice" },
	{ name = "*.doc", use = "onlyoffice" },
	{ name = "*.docx", use = "onlyoffice" },
	{ name = "*.xls", use = "onlyoffice" },
	{ name = "*.xlsx", use = "onlyoffice" },
	{ name = "*.ppt", use = "onlyoffice" },
	{ name = "*.pptx", use = "onlyoffice" },
	{ name = "*.ods", use = "onlyoffice" },
	{ name = "*.odt", use = "onlyoffice" },
	{ name = "*.odp", use = "onlyoffice" },

	{ name = "*.json", use = "edit" },
	{ name = "*.sh", use = "edit" },
	{ name = "*.toml", use = "edit" },
	{ name = "*.y*ml", use = "edit" },
	{ name = "*config", use = "edit" },
	{ name = "*.cfg", use = "edit" },
	{ name = "*env", use = "edit" },
	{ name = "*.d", use = "edit" },
	{ name = "*.md", use = "edit" },
	{ name = "*.txt", use = "edit" },
	{ name = ".zsh*", use = "edit" },
	{ name = "*.ini", use = "edit" },
	{ name = "*.lua", use = "edit" },
	{ name = "*.xml", use = "edit" },
	{ name = "*.log", use = "edit" },

	{ name = "*.pdf", use = "open" },
]

append_rules = [
	{ name = "*", use = "edit" },
]
